"""empty message

Revision ID: 5e78cc772642
Revises: ec21bd75ea92
Create Date: 2020-07-22 22:44:45.754328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e78cc772642'
down_revision = 'ec21bd75ea92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.Text(), nullable=True),
    sa.Column('recipe_link', sa.Text(), nullable=True),
    sa.Column('image_link', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('servings', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('recipes')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'ingredients', 'recipe', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'saved_recipes', type_='foreignkey')
    op.drop_constraint(None, 'saved_recipes', type_='foreignkey')
    op.create_foreign_key(None, 'saved_recipes', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'saved_recipes', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_recipes', type_='foreignkey')
    op.drop_constraint(None, 'saved_recipes', type_='foreignkey')
    op.create_foreign_key(None, 'saved_recipes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'saved_recipes', 'recipes', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'ingredients', 'recipes', ['recipe_id'], ['id'])
    op.create_table('recipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_name', sa.TEXT(), nullable=True),
    sa.Column('recipe_link', sa.TEXT(), nullable=True),
    sa.Column('image_link', sa.TEXT(), nullable=True),
    sa.Column('instructions', sa.TEXT(), nullable=True),
    sa.Column('servings', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('recipe')
    # ### end Alembic commands ###
